language: ruby
rvm:
  - 2.3.3
python:
  - "3.5"
cache:
  pip: true
  bundler: true
  directories:
  - /home/travis/.rvm/
install:
  - pip install --user awscli
  - bundle install
script:
  - ./script/ci:build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
  - testing
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET
    skip_cleanup: true
    local_dir: _site
    region: $AWS_REGION
    cache_control: "max-age=21600"
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_TESTING
    skip_cleanup: true
    local_dir: _site
    region: $AWS_REGION_TESTING
    cache_control: "max-age=21600"
    on:
      branch: testing

after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - test $TRAVIS_BRANCH = "testing" && aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID_TESTING --paths "/*"
sudo: false
