language: ruby
rvm:
  - 2.3.3
python:
  - "3.5"
cache:
  pip: true
  bundler: true
  directories:
  - /home/travis/.rvm/
  - ./functions/origin-request/node_modules/
install:
  - pip install --user awscli
  - bundle install
script:
  - ./script/build-pages
  - ./script/build-functions
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
  - testing
deploy:
  - provider: script
    script: bash script/deploy
    on:
      branch: testing
sudo: false
