language: node_js
node_js:
  - "10"
rvm:
  - 2.3.3
python:
  - "3.5"
cache:
  pip: true
  bundler: true
  directories:
  - /home/travis/.rvm/
  - ./functions/origin-request/node_modules/
jobs:
  include:
    - stage: test
      script: ./script/test-functions
    - stage: build-and-deploy
      install:
        - pip install --user awscli
        - bundle install
      script: ./script/build
      script: ./script/deploy
stages:
  - test
  - build-and-deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
  - testing
sudo: false
