title: nickmeldrum.com
email: nick@nickmeldrum.com
description: >-
  Nick Meldrum's blog
  and little corner of the interwebs
baseurl: ""
url: "https://nickmeldrum.com"
twitter_username: jekyllrb
github_username:  jekyll
encoding: utf-8
gems: [jekyll-paginate]

paginate_path: "blog/page:num/"
paginate: 5
permalink: blog/:title/
markdown: kramdown
highlighter: rouge

source: site
destination: _site
sass:
  style: compressed
