title: nickmeldrum.com
email: nick@nickmeldrum.com
description: >-
  Nick Meldrum's blog
  and little corner of the interwebs
baseurl: ""
url: "https://nickmeldrum.com"
twitter_username: jekyllrb
github_username:  jekyll
encoding: utf-8

paginate_path: "blog/page:num/"
permalink: blog/:title/
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

markdown: kramdown
source: site
destination: _site
sass:
  style: compressed
