production_url: 'https://nickmeldrum.com'
baseurl: ''
encoding: utf-8
plugins:
  - jekyll-paginate-v2
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num.html'
  title: 'Articles - page :num'
  sort_reverse: true
permalink: 'blog/:title'
markdown: kramdown
highlighter: rouge
source: site
destination: 'dist/_site'
sass:
  style: compressed
twitter_username: 'nick_meldrum'
github_username:  'nickmeldrum'
